# Generated by Django 4.1.1 on 2022-10-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_administratorprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisorprofile',
            old_name='teacher_id',
            new_name='Supervisor_id',
        ),
    ]
