# Generated by Django 4.1.1 on 2022-10-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_operator_alter_user_role_operatorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'SuperAdmin'), ('ADMINISTRATOR', 'Administrator'), ('SUPERVISOR', 'Supervisor'), ('OPERATOR', 'Operator')], max_length=50),
        ),
    ]
