# Generated by Django 4.1.2 on 2022-11-02 14:26

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperatorProfile',
            new_name='SuperadminProfile',
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
        migrations.CreateModel(
            name='Superadmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('Superadmin', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OPERATOR', 'Operator'), ('ADMINISTRATOR', 'Administrator'), ('SUPERVISOR', 'Supervisor'), ('SUPERADMIN', 'Superadmin')], max_length=50),
        ),
    ]
